name: Android KMP CI/CD 

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  ANDROID_SDK_VERSION: '34'
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  setup:
    name: Setup Environment
    runs-on: macos-latest
    outputs:
      gradle-cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Accept licenses and install SDK components
        run: |
          echo "y" | sudo $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          sudo $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-${ANDROID_SDK_VERSION}" \
            "build-tools;34.0.0"

      - name: Add Android tools to PATH
        run: |
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Generate Gradle cache key
        id: cache-key
        run: echo "key=gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}" >> $GITHUB_OUTPUT

  build:
    name: Build Project
    runs-on: macos-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs.gradle-cache-key }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

  test:
    name: Run Unit Tests
    runs-on: macos-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs.gradle-cache-key }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

  lint:
    name: Run Lint
    runs-on: macos-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs.gradle-cache-key }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Run lint
        run: ./gradlew lintDebug

  assemble:
    name: Assemble APK
    runs-on: macos-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs.gradle-cache-key }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Assemble APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
