name: Build KMP Project (Android Only)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  java-setup:
    name: Java Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

  android-sdk:
    name: Android SDK Setup
    runs-on: ubuntu-latest
    needs: java-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

  permission-check:
    name: Gradle Permission
    runs-on: ubuntu-latest
    needs: android-sdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

  build-android:
    name: Build Android App
    runs-on: ubuntu-latest
    needs: permission-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Android app
        run: ./gradlew assembleDebug

  test-android:
    name: Run Android Tests
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Android tests
        run: ./gradlew allTests

